name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --verbosity normal

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Get the commit SHA
      id: commit_sha
      run: echo ::set-output name=sha::$(git rev-parse --short ${{ github.sha }})

    - name: Build and Push Docker image
      run: |
        docker build -t mertkont/learnboxapi:${{ steps.commit_sha.outputs.sha }} .
        docker push mertkont/learnboxapi:${{ steps.commit_sha.outputs.sha }}

